/**
 * 
 */
package com.petstore.model.bo;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User details.
 * 
 * @author analian
 */
@Entity
@Table(name = "USER")
public class User implements Serializable
{

   /**
    * Autogenerated for serializable class.
    */
   private static final long serialVersionUID = 7798456708767544819L;

   /**
    * ID column
    */
   @Id
   @GeneratedValue(strategy = GenerationType.AUTO)
   @Column(name = "ID")
   private int user_id;
   /**
    * First name
    */
   @Column(name = "FIRST_NAME")
   private String first_name;
   /**
    * Last name
    */
   @Column(name = "LAST_NAME")
   private String last_name;
   /**
    * email id
    */
   @Column(name = "EMAIL_ID")
   private String email_id;
   /**
    * user name
    */
   @Column(name = "USERNAME")
   private String username;
   /**
    * password
    */
   @Column(name = "PASSWORD")
   private String password;
   /**
    * address
    */
   @Column(name = "ADDRESS")
   private String address;
   /**
    * city
    */
   @Column(name = "CITY")
   private String city;
   /**
    * pins
    */
   @Column(name = "PIN")
   private String pin;

   @Column(name = "IS_ADMIN")
   private boolean adminUser;

   /**
    * @return the user_id
    */
   public int getUser_id()
   {
      return user_id;
   }

   /**
    * @param user_id the user_id to set
    */
   public void setUser_id(int user_id)
   {
      this.user_id = user_id;
   }

   /**
    * @return the first_name
    */
   public String getFirst_name()
   {
      return first_name;
   }

   /**
    * @param first_name the first_name to set
    */
   public void setFirst_name(String first_name)
   {
      this.first_name = first_name;
   }

   /**
    * @return the last_name
    */
   public String getLast_name()
   {
      return last_name;
   }

   /**
    * @param last_name the last_name to set
    */
   public void setLast_name(String last_name)
   {
      this.last_name = last_name;
   }

   /**
    * @return the email_id
    */
   public String getEmail_id()
   {
      return email_id;
   }

   /**
    * @param email_id the email_id to set
    */
   public void setEmail_id(String email_id)
   {
      this.email_id = email_id;
   }

   /**
    * @return the username
    */
   public String getUsername()
   {
      return username;
   }

   /**
    * @param username the username to set
    */
   public void setUsername(String username)
   {
      this.username = username;
   }

   /**
    * @return the password
    */
   public String getPassword()
   {
      return password;
   }

   /**
    * @param password the password to set
    */
   public void setPassword(String password)
   {
      this.password = password;
   }

   /**
    * @return the address
    */
   public String getAddress()
   {
      return address;
   }

   /**
    * @param address the address to set
    */
   public void setAddress(String address)
   {
      this.address = address;
   }

   /**
    * @return the city
    */
   public String getCity()
   {
      return city;
   }

   /**
    * @param city the city to set
    */
   public void setCity(String city)
   {
      this.city = city;
   }

   /**
    * @return the pin
    */
   public String getPin()
   {
      return pin;
   }

   /**
    * @param pin the pin to set
    */
   public void setPin(String pin)
   {
      this.pin = pin;
   }

   /**
    * @return the adminUser
    */
   public boolean isAdminUser()
   {
      return adminUser;
   }

   /**
    * @param adminUser the adminUser to set
    */
   public void setAdminUser(boolean adminUser)
   {
      this.adminUser = adminUser;
   }

   /**
    * @return the serialversionuid
    */
   public static long getSerialversionuid()
   {
      return serialVersionUID;
   }

}
